Add first plugins from Meilisearch
kestra-io/plugin-meilisearch pull request #2
Opened 2024-09-03 16:00 UTC by mgabelle

### What changes are being made and why?

Add plugins from Meilisearch :

- DocumentAdd
- DocumentGet
- Search
- FacetSearch

---

### How the changes have been QAed?

---

### Setup Instructions

2024-09-03 16:31 UTC, loicmathieu requested changes
DocumentGet return and object but DocumentAdd take a file, maybe DocumentGte should be a file?

When searching, you get objects ... should'n'y it be Maps instead?

2024-09-03 16:31 UTC, loicmathieu commented on build.gradle
>      api "com.google.code.gson:gson:2.11.0"
```suggestion
```

2024-09-03 16:31 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/meilisearch/DocumentAdd.java
> +                    index: \\"index where we want to add the document\\"
```suggestion
                """
                    document: "document to be added in JSON"
                    URL:  "url of the meilisearch server"
                    key:  "masterKey of the meilisearch server"
                    index: "index where we want to add the document"
```

Java text block allow to use double-quotes inside them.
Moreover, we usually provide a "working example" not an example with description of the properties.

2024-09-03 16:31 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/meilisearch/DocumentAdd.java
> +        }
The try/catch is not needed if you didn't do anything specific about it as we will already log it

2024-09-03 16:31 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/meilisearch/FacetSearch.java
> +    private String[] filters;
Use  List<String> itself, moreover don't forget to render it!

2024-09-03 17:09 UTC, fhussonnois reviewed
Minor comment, for commit messages we follow this convention: https://www.conventionalcommits.org/

2024-09-03 17:09 UTC, fhussonnois commented on src/main/java/io/kestra/plugin/meilisearch/AbstractMeilisearchConnection.java
> +    public MeilisearchFactory meilisearchFactory(RunContext runContext) throws IllegalVariableEvaluationException {
It seems that you always use the same pattern, in the child classes, i.e., : 

```java
        MeilisearchFactory factory = this.meilisearchFactory(runContext);
        Client client = factory.getMeilisearchClient();
```

Could be more simple to just create a static factory method `createClient(RunContext)` that directly returns the `Client`.  Creating an internal `MeilisearchFactory` class doesn't seem relevant here.

2024-09-04 06:07 UTC, mgabelle commented on build.gradle
>      api "com.google.code.gson:gson:2.11.0"
Thanks for catching this. 
I am wondering should I store DocumentGet in a ion file or return it like that ? 
Also kind of the same question with DocumentAdd, should I get it from a "json string" or should I except a file link ?

2024-09-04 07:39 UTC, mgabelle commented on src/main/java/io/kestra/plugin/meilisearch/FacetSearch.java
> +    private String[] filters;
Changed to List<String> and use render

2024-09-04 07:40 UTC, mgabelle commented on src/main/java/io/kestra/plugin/meilisearch/AbstractMeilisearchConnection.java
> +    public MeilisearchFactory meilisearchFactory(RunContext runContext) throws IllegalVariableEvaluationException {
Sure you're right

2024-09-04 07:51 UTC, mgabelle commented on src/main/java/io/kestra/plugin/meilisearch/DocumentAdd.java
> +        }
Removed

2024-09-05 07:39 UTC, loicmathieu requested changes

2024-09-05 07:39 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/meilisearch/FacetSearch.java
> +        double hitSize = 0.0;
It's strange that the number of hit is a double, can you match half a document?
Better to be an int or a long (depending on what is supported by Meilisearch).

2024-09-05 07:39 UTC, loicmathieu commented on build.gradle
> +    implementation 'org.json:json:20211205'
Can you remove the json library if not used?

2024-09-09 13:58 UTC, mgabelle commented on src/main/java/io/kestra/plugin/meilisearch/DocumentAdd.java
> +                    index: \\"index where we want to add the document\\"
Added explicit flows

2024-09-09 13:58 UTC, mgabelle commented on build.gradle
> +    implementation 'org.json:json:20211205'
done

2024-09-09 13:59 UTC, mgabelle commented on src/main/java/io/kestra/plugin/meilisearch/FacetSearch.java
> +        double hitSize = 0.0;
Yes, the api return a Double..that's weird..
Converted to Long

2024-09-10 07:37 UTC, loicmathieu requested changes

2024-09-10 07:37 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/meilisearch/DocumentAdd.java
> +            .build();
Outputs are designed to be used by other tasks.
Here it looks like a log so I'd rather log that at info level (via the runnerCOntext.logger), and use a VoidOutput and return null.

2024-09-10 07:37 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/meilisearch/DocumentAdd.java
> +    @PluginProperty(dynamic = true)
`@PluginProperty` are not needed when using `Property` based attributes, please remove them everywhere.

2024-09-10 07:37 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/meilisearch/DocumentGet.java
> +        private final Map document;
```suggestion
        private final Map<String, Object> document;
```

2024-09-10 07:37 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/meilisearch/FacetSearch.java
> +            Flux<FacetSearchable> hitFlux = Flux.just(results);
```suggestion
            Flux<FacetSearchable> hitFlux = Flux.fromIterable(results);
```

Flux.just() will emit a single element, so if you have a list you want to emit multiple elements so each element will be serialized as a separate object so each element will be in its own line
Here, you serialize all elements into a big array into a single line.

2024-09-10 07:37 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/meilisearch/FacetSearch.java
> +        private final Long totalHits;
Please add documentation via `@Schema`

2024-09-10 07:37 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/meilisearch/Search.java
> +        ArrayList<HashMap<String, Object>> hits = results.getHits();
```suggestion
        List<HashMap<String, Object>> hits = results.getHits();
```

Best practice: code against interface

2024-09-10 07:37 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/meilisearch/Search.java
> +        private final Long totalHits;
Please add documentaiton via `@Schema`

2024-09-10 12:02 UTC, mgabelle commented on src/main/java/io/kestra/plugin/meilisearch/FacetSearch.java
> +            Flux<FacetSearchable> hitFlux = Flux.just(results);
Actually the result returned by facetSearch is always one JSON document like below :  
That's why I just put `Flux.just`. But I will rename `results` to `result`.

Example: 
`{
  "facetHits":[
    {
      "value":"fiction",
      "count":7
    }
  ],
  "facetQuery":"fiction",
  "processingTimeMs":0
}`

2024-09-10 12:12 UTC, mgabelle commented on src/main/java/io/kestra/plugin/meilisearch/DocumentAdd.java
> +            .build();
Use log and remove Output to VoidOutput

2024-09-10 12:21 UTC, mgabelle commented on src/main/java/io/kestra/plugin/meilisearch/DocumentAdd.java
> +    @PluginProperty(dynamic = true)
Removed

2024-09-10 12:23 UTC, mgabelle commented on src/main/java/io/kestra/plugin/meilisearch/DocumentGet.java
> +        private final Map document;
Changed to `Map<String, Object>`

2024-09-10 14:20 UTC, mgabelle commented on src/main/java/io/kestra/plugin/meilisearch/FacetSearch.java
> +        private final Long totalHits;
Added docs

2024-09-10 14:20 UTC, mgabelle commented on src/main/java/io/kestra/plugin/meilisearch/Search.java
> +        private final Long totalHits;
Added docs

2024-09-13 07:44 UTC, loicmathieu approved these changes
LGTM

2024-09-13 11:14 UTC, merged